export const ACTIONS = {
  // INPUT_CHANGE: 'INPUT_CHANGE',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  LIKE_PRODUCTS: 'LIKE_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  ADD_REVIEW: 'ADD_REVIEW',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',
};
